inherit_from: .rubocop_todo.yml

# Excludeに設定したファイルは、チェック対象外になる
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    # - 'db/**/*'
    # - 'config/**/*'
    # - 'spec/rails_helper.rb'
    # - 'spec/spec_helper.rb'
